import * as T from 'three';
import {pictureBooks} from './children-data.js';
import {createPopUpWorld} from './pop-up-world.js';
import './children.css';
import {createBookOpening} from './book-opening.js';
export function createChildren({scene,camera,renderer,controls,S}){
 const root=document.createElement('section');root.id='children-experience';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','立体绘本馆');
 root.innerHTML=`<header class="child-header"><div class="child-brand">小小世界 · 绘本馆<small>STORIES THAT COME TO LIFE</small></div><nav class="child-tabs"><button id="children-library">三本绘本</button></nav><button id="children-close">合上 · 回书房</button></header><div class="child-gallery"><div class="child-intro"><span class="eyebrow">THE POP-UP COLLECTION / VOL. 01—03</span><h1>翻开一本，遇见一个小世界</h1><p>摸得到的纸纹，看得见的想象。选一本书，让故事从纸上站起来。</p></div><div class="cover-grid"></div><div class="gallery-foot"><span>3 本原创绘本 · 12 幕故事 · 12 段中文朗读 · 12 个互动提问</span><span>每一页，都藏着一个等你发现的小惊喜</span></div></div><div class="child-reader"><div class="child-reader-top"><div class="child-title-group"><img class="child-cover-thumb" alt="绘本封面"><h2 id="child-title"></h2></div><span id="child-tag"></span></div><div class="child-layout"><div><div class="popup-shell"><div class="popup-caption">拖一拖，看见纸页里的小世界</div><div class="story-bubble" aria-live="polite"></div><div class="popup-stage"></div><div class="popup-controls"><button id="animal-action"></button><span id="animal-feedback" role="status">也可以直接点一下动物</span></div></div><div class="child-question"><h4></h4><div class="child-choices"></div><div class="question-feedback" role="status"></div></div></div><article class="child-paper"><div class="chapter-kicker"></div><h3 id="child-chapter-title"></h3><div class="child-story"></div><div class="child-fact"></div><div class="narration-bar"><audio id="child-audio" controls preload="metadata"></audio><small>温柔朗读 · 点击播放 · 翻页时暂停</small></div><div class="child-pagination"><button id="child-prev">← 上一幕</button><div class="child-dots"></div><button id="child-next">下一幕 →</button></div></article></div><p class="children-note">这是浏览器内的 3D 立体绘本，无需摄像头；并非现实空间定位 AR。月球故事包含童话想象。</p></div>`;
 document.body.append(root);const $=s=>root.querySelector(s),audio=$('#child-audio');let active=false,index=0,chapter=0,previousFocus=null,answers={};try{answers=JSON.parse(localStorage.getItem('afterhours.children.answers')||'{}')}catch{}
 const opening=createBookOpening();let turnTimer=null,turnEndTimer=null,flipTimer=null,pickedRoomBook=null;
 const world=createPopUpWorld($('.popup-stage'),feedback,(i,rect)=>openBook(i,rect));
 const descriptions=['和栗栗穿过夜色，学会求助与分享。点亮萤火，找到回家的路。','和蓝蓝游进珊瑚花园，听海的声音，给海洋动物留一条干净的路。','陪米米在月面播下一颗想象的种子，跳一跳，练习等待与观察。'];
 pictureBooks.forEach((b,i)=>{const button=document.createElement('button');button.className='cover-choice';button.dataset.pictureBook=i;button.setAttribute('aria-label','打开《'+b.title+'》');button.innerHTML=`<div class="child-cover" style="--cover-bg:${b.color};--cover-text:${i===2?'#fff0bd':'#264f48'}"><img src="${b.cover}" alt="${b.title}封面"><div class="cover-type"><small>LITTLE WORLDS · ${String(i+1).padStart(2,'0')}</small><h2>${b.title.slice(0,i===2?4:3)}<br>${b.title.slice(i===2?4:3)}</h2><p>${b.tag}</p></div><div class="cover-footer">一本可以听、可以玩的立体绘本</div></div><div class="cover-meta"><span>${b.age} · 亲子共读</span><span>4 幕 · 3D + 朗读 ↗</span></div><div class="cover-description">${descriptions[i]}</div>`;button.onclick=()=>openBook(i);$('.cover-grid').append(button)});
 function stopAudio(){audio.pause();try{audio.currentTime=0}catch{}}
 function block(v){S.readerOpen=v;S.typing=v;controls.enabled=!v;renderer.domElement.style.pointerEvents=v?'none':'auto';}
 function open(i){if(i!==undefined){pickedRoomBook=picks.find(p=>p.userData.childBook===i)?.parent;if(pickedRoomBook)pickedRoomBook.visible=false;}previousFocus=document.activeElement;active=true;block(true);if(i===undefined){root.classList.add('visible');gallery();}else openBook(i,roomRect(i));$('#children-close').focus()}
 function close(){if(pickedRoomBook)pickedRoomBook.visible=true;pickedRoomBook=null;opening.cancel();clearTimeout(turnTimer);clearTimeout(turnEndTimer);clearTimeout(flipTimer);turnTimer=null;$('.child-layout').classList.remove('turning');root.classList.remove('folding');stopAudio();active=false;root.classList.remove('visible','reading');block(false);world.setActive(false);previousFocus?.focus()}
 function gallery(){root.classList.remove('reading');if(pickedRoomBook)pickedRoomBook.visible=true;pickedRoomBook=null;opening.cancel();clearTimeout(turnTimer);clearTimeout(turnEndTimer);clearTimeout(flipTimer);turnTimer=null;$('.child-layout').classList.remove('turning');root.classList.remove('folding');stopAudio();world.setActive(false);$('.child-gallery').style.display='block';$('.child-reader').classList.remove('visible');$('#children-library').classList.add('active')}
 function openBook(i,rect){if(opening.snapshot()!=='idle')return;clearTimeout(turnTimer);clearTimeout(turnEndTimer);clearTimeout(flipTimer);turnTimer=null;root.classList.remove('folding');$('.child-layout').classList.remove('turning');stopAudio();const cover=root.querySelectorAll('.child-cover')[i];const start=rect||cover.getBoundingClientRect();opening.run(cover,start,()=>{showBook(i);});}
 function showBook(i){root.classList.add('visible','reading');index=i;chapter=0;try{const value=Number(localStorage.getItem('afterhours.children.chapter.'+i));if(Number.isInteger(value)&&value>=0&&value<4)chapter=value}catch{}$('.child-gallery').style.display='none';$('.child-reader').classList.add('visible');$('#children-library').classList.remove('active');renderChapter();world.setActive(true);$('.child-reader').classList.remove('entering');void $('.child-reader').offsetWidth;$('.child-reader').classList.add('entering');root.scrollTop=0;}
 function renderChapter(){stopAudio();const b=pictureBooks[index],c=b.chapters[chapter];$('#child-title').textContent=b.title;$('#child-tag').textContent=b.age+' / '+b.tag;$('.child-cover-thumb').src=b.cover;$('.chapter-kicker').textContent='CHAPTER '+String(chapter+1).padStart(2,'0')+' / 04 · '+b.tag;$('#child-chapter-title').textContent=c.title;$('.child-story').replaceChildren(...c.text.map(t=>{const p=document.createElement('p');p.textContent=t;return p}));$('.child-fact').textContent='小小知识卡 · '+c.fact;audio.src=`${import.meta.env.BASE_URL}audio-edge/${b.id}-${chapter}.mp3`;audio.load();$('#animal-action').textContent=b.action;$('#animal-feedback').textContent='点一下'+b.animal+'，听听它想说什么';$('.story-bubble').textContent=c.title;$('.story-bubble').classList.remove('speaking');$('.child-question h4').textContent=c.question;$('.question-feedback').textContent='想一想，选一个答案吧。';$('.child-choices').replaceChildren(...c.choices.map((label,i)=>{const button=document.createElement('button');button.textContent=label;button.dataset.answer=i;button.onclick=()=>answer(i);return button}));const key=b.id+'-'+chapter;if(answers[key]===true){$('.child-choices').children[c.answer].classList.add('correct');$('.question-feedback').textContent='✦ 已收集一枚故事星星 · '+c.response;}$('#child-prev').disabled=chapter===0;$('#child-next').disabled=chapter===3;$('.child-dots').replaceChildren(...b.chapters.map((_,i)=>{const button=document.createElement('button');button.textContent=i+1;button.classList.toggle('active',i===chapter);button.setAttribute('aria-label','第'+(i+1)+'幕');button.onclick=()=>turn(i);return button}));world.load(b.id,chapter);try{localStorage.setItem('afterhours.children.chapter.'+index,chapter)}catch{}}
 function turn(n){if(n<0||n>3||n===chapter||turnTimer)return;stopAudio();world.fold();root.classList.add('folding');flipTimer=setTimeout(()=>{world.flip();$('.child-layout').classList.add('turning');},550);turnTimer=setTimeout(()=>{chapter=n;renderChapter();root.classList.remove('folding');},1320);turnEndTimer=setTimeout(()=>{$('.child-layout').classList.remove('turning');turnTimer=null;},1750);}
 function answer(i){const b=pictureBooks[index],c=b.chapters[chapter];const correct=i===c.answer;$('.child-choices').children[i].classList.add(correct?'correct':'incorrect');$('.question-feedback').textContent=correct?'✦ 收到一枚故事星星！'+c.response:'再想一想，也可以先听一遍故事。';if(correct){answers[b.id+'-'+chapter]=true;try{localStorage.setItem('afterhours.children.answers',JSON.stringify(answers))}catch{}world.interact()}}
 let toneContext;function feedback(){const b=pictureBooks[index];const lines={fox:['天黑了，你愿意陪我找一盏光吗？','小桥有点滑，我们慢慢走。','原来小小的光，也能照亮一条路！','把光分给朋友，夜晚就不怕黑了。'],whale:['你听见海里的声音了吗？','珊瑚花园里，每个朋友都有自己的声音。','我们给海龟留一条干净的路。','我找到了！这是我们一起唱的歌。'],rabbit:['我到月亮啦！一起轻轻跳一下？','慢一点，让身体慢慢落下来。','今天也给想象的种子一点水。','等一等，星光真的开花了！']};$('.story-bubble').textContent=lines[b.id][chapter];$('.story-bubble').classList.add('speaking');$('#animal-feedback').textContent=['栗栗转过身来，萤火亮起来了。','蓝蓝摆了摆尾巴：你好，海洋朋友！','米米轻轻一跳，慢慢落回月面。'][index];try{toneContext??=new AudioContext();toneContext.resume();const osc=toneContext.createOscillator(),gain=toneContext.createGain();osc.type='sine';osc.frequency.setValueAtTime(index===1?180:620,toneContext.currentTime);osc.frequency.exponentialRampToValueAtTime(index===1?100:930,toneContext.currentTime+.4);gain.gain.setValueAtTime(.04,toneContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,toneContext.currentTime+.5);osc.connect(gain);gain.connect(toneContext.destination);osc.start();osc.stop(toneContext.currentTime+.5);osc.onended=()=>{osc.disconnect();gain.disconnect()}}catch{}}
 $('#animal-action').onclick=()=>{world.interact();feedback()};$('#child-prev').onclick=()=>turn(chapter-1);$('#child-next').onclick=()=>turn(chapter+1);$('#children-close').onclick=close;$('#children-library').onclick=gallery;
 document.addEventListener('keydown',e=>{if(!active)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close()}if(e.key==='Tab'){const els=[...root.querySelectorAll('button,audio')].filter(x=>!x.disabled&&x.offsetParent!==null);if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0].focus()}}},true);
 const entry=document.createElement('button');entry.id='children-entry';entry.innerHTML='打开儿童立体绘本馆<small>3 本绘本 · 动物 · 故事 · 朗读</small>';entry.onclick=()=>open();document.querySelector('#side').prepend(entry);
 // Three front-facing illustrated books are also available directly in the room.
 function roomRect(i){const obj=picks.find(p=>p.userData.childBook===i);if(!obj)return null;const p=obj.getWorldPosition(new T.Vector3()).project(camera);return{left:(p.x+1)*innerWidth/2-35,top:(1-p.y)*innerHeight/2-50,width:70,height:100};}
 const picks=[];const loader=new T.TextureLoader();pictureBooks.forEach((b,i)=>{const group=new T.Group();group.position.set(1.6+i*1.15,1.4,-5.72);group.rotation.y=-.12;scene.add(group);const coverMat=new T.MeshStandardMaterial({color:b.color,roughness:.84});const volume=new T.Mesh(new T.BoxGeometry(.9,1.3,.12),coverMat);volume.castShadow=true;group.add(volume);const pages=new T.Mesh(new T.BoxGeometry(.85,1.25,.07),new T.MeshStandardMaterial({color:'#eadfc9',roughness:.95}));pages.position.z=.07;group.add(pages);loader.load(b.cover,texture=>{const canvas=document.createElement('canvas');canvas.width=600;canvas.height=900;const ctx=canvas.getContext('2d');ctx.drawImage(texture.image,0,0,600,900);ctx.textAlign='center';ctx.fillStyle=i===2?'#fff0bd':'#264f48';ctx.font='bold 35px "Songti SC"';ctx.fillText(b.title.slice(0,i===2?4:3),310,90);ctx.fillText(b.title.slice(i===2?4:3),310,145);ctx.font='14px sans-serif';ctx.fillText(b.tag,310,181);const tex=new T.CanvasTexture(canvas);tex.colorSpace=T.SRGBColorSpace;const front=new T.Mesh(new T.PlaneGeometry(.9,1.3),new T.MeshStandardMaterial({map:tex,roughness:.92}));front.position.z=.12;front.userData.childBook=i;group.add(front);picks.push(front);texture.dispose()})});
 const ledge=new T.Mesh(new T.BoxGeometry(4,.13,.6),new T.MeshStandardMaterial({color:'#896e4c',roughness:.85}));ledge.position.set(2.8,.72,-5.72);scene.add(ledge);const light=new T.PointLight('#ffe0a4',9,6,2);light.position.set(2.7,2.5,-4.5);scene.add(light);
 const ray=new T.Raycaster();let down=null;renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(active||S.readerOpen||S.noteOpen||!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>7)return;ray.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const hit=ray.intersectObjects(picks)[0];if(hit)open(hit.object.userData.childBook)});
 if(new URLSearchParams(location.search).get('library')==='children')open();
 return{update:(t,dt)=>world.update(t,dt),snapshot:()=>({active,index,chapter,title:pictureBooks[index].title,audioPaused:audio.paused,audioTime:+audio.currentTime.toFixed(2),audioDuration:Number.isFinite(audio.duration)?+audio.duration.toFixed(2):null,answers:Object.keys(answers).length,openingPhase:opening.snapshot(),...world.snapshot()})};
}
