import * as THREE from 'three';
import './immersive.css';
import {library} from './chapters.js';
import {createWeather} from './weather.js';

// V2 interaction design and implementation by Codex, on the documented Atria V1 scene.
export function createImmersive(env){
 const {scene,camera,controls,renderer,S,bookMeshes,note,pen,DESK,WIN,ROOM,glass,sky,rain,toast}=env;
 const $=s=>document.querySelector(s);let mode=null,chapter=0,bookIndex=0,flight=null,selectedSource=null,returnFocus=null,openTimer=null;
 const textureLoader=new THREE.TextureLoader();const art=library.map(b=>{const t=textureLoader.load(b.image);t.colorSpace=THREE.SRGBColorSpace;return t;});
 const bookUI=document.createElement('section');bookUI.id='book-experience';bookUI.className='immersive-layer';bookUI.setAttribute('role','dialog');bookUI.setAttribute('aria-modal','true');bookUI.setAttribute('aria-label','翻阅书籍');
 bookUI.innerHTML=`<button id="return-book" class="experience-close">合上 · 放回书架</button><div class="book-object"><div class="book-binding"><div class="book-spread"><div class="book-left"><div class="book-eyebrow">After hours · Illustrated collection</div><h2 id="volume-title"></h2><p class="book-subtitle"></p><img class="book-art" alt="书内插图"><p class="book-art-credit">插图由 Codex Image 生成</p><span class="page-number">左页 · 插图</span></div><div class="book-right"><div class="book-eyebrow">A quiet moment, a page at a time</div><h3 class="book-chapter"></h3><div class="book-copy"></div><span class="page-number" id="page-count"></span></div><div class="turn-leaf"></div></div></div><div class="book-nav"><button id="prev-chapter">← 上一章</button><select class="chapter-select" aria-label="选择章节"></select><button id="next-chapter">下一章 →</button></div></div>`;
 document.body.append(bookUI);
 const writing=document.createElement('section');writing.id='writing-experience';writing.className='immersive-layer';writing.setAttribute('role','dialog');writing.setAttribute('aria-modal','true');writing.setAttribute('aria-label','手写纸面');
 writing.innerHTML=`<button id="return-paper" class="experience-close">放回纸笔</button><div class="writing-board"><div class="writing-heading"><div><h2>把想法留在纸上</h2><p>鼠标、触摸或压感笔，自由落笔。</p></div><span style="font:10px Georgia;letter-spacing:.2em;color:#bba77e">FIELD NOTES / 01</span></div><div class="paper-frame"><canvas id="ink-canvas" width="1200" height="800" aria-label="手写画布"></canvas><div class="pen-cursor"></div></div><div class="writing-toolbar"><div class="ink-colors"><button class="active" data-ink="#263c33" style="--ink-color:#263c33" aria-label="墨绿墨水"></button><button data-ink="#284d73" style="--ink-color:#284d73" aria-label="蓝色墨水"></button><button data-ink="#944b3e" style="--ink-color:#944b3e" aria-label="赭红墨水"></button></div><label>笔尖 <input id="ink-size" type="range" min="1" max="8" value="3" aria-label="笔尖粗细"></label><button id="ink-undo">撤销</button><button id="ink-redo">重做</button><button id="ink-clear">清空</button><button id="ink-save">保存笔迹</button><button id="ink-export">导出 PNG</button><span class="ink-status" role="status">纸面已准备好</span></div><div class="writing-hint">保存后，笔迹会留在桌面纸张上；刷新页面仍可继续。Esc 放回纸笔。</div></div>`;
 document.body.append(writing);
 const canvas=$('#ink-canvas'),ctx=canvas.getContext('2d'),cursor=$('.pen-cursor');const W=1200,H=800;
 const INK_KEY='afterhours.handwriting.v2';let strokes=[],redo=[],active=null,ink='#263c33',size=3,dirty=false,revision=0;
 try{const saved=JSON.parse(localStorage.getItem(INK_KEY)||'[]');if(Array.isArray(saved))strokes=saved.filter(s=>Array.isArray(s.points)&&s.points.length&&typeof s.color==='string').slice(-800);}catch{}
 const paperTextureCanvas=document.createElement('canvas');paperTextureCanvas.width=W;paperTextureCanvas.height=H;const pctx=paperTextureCanvas.getContext('2d');const paperTex=new THREE.CanvasTexture(paperTextureCanvas);paperTex.colorSpace=THREE.SRGBColorSpace;
 // A full-sized sheet and a fountain pen replace the small text-only sticky note.
 note.geometry.dispose();note.geometry=new THREE.PlaneGeometry(1.38,.92);note.rotation.set(-Math.PI/2,0,.09);note.position.set(DESK.x-.35,DESK.top+.065,DESK.z+.25);note.userData.baseY=note.position.y;note.material.map=paperTex;note.material.needsUpdate=true;
 env.openBook.visible=false;pen.scale.set(1.6,2.1,1.6);pen.position.set(DESK.x+.65,DESK.top+.07,DESK.z+.3);pen.userData.note=true;pen.userData.hoverable=true;
 for(let i=0;i<4;i++){const sheet=new THREE.Mesh(new THREE.BoxGeometry(1.42,.008,.95),new THREE.MeshStandardMaterial({color:0xe7dbc1,roughness:.96}));sheet.position.set(note.position.x+i*.012,DESK.top+.04+i*.005,note.position.z);sheet.rotation.y=.09+i*.006;scene.add(sheet);}
 function drawStroke(c,s){if(!s.points.length)return;c.strokeStyle=s.color;c.fillStyle=s.color;c.lineCap='round';c.lineJoin='round';const points=s.points;
  if(points.length===1){const p=points[0];c.beginPath();c.arc(p.x*W,p.y*H,s.size*.65,0,Math.PI*2);c.fill();return;}
  for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];c.lineWidth=s.size*(.6+(b.p||.5)*1.15);c.beginPath();c.moveTo(a.x*W,a.y*H);c.lineTo(b.x*W,b.y*H);c.stroke();}
 }
 function redraw(){ctx.clearRect(0,0,W,H);for(const s of strokes)drawStroke(ctx,s);if(active)drawStroke(ctx,active);}
 function updatePaper(){pctx.fillStyle='#efe5cc';pctx.fillRect(0,0,W,H);pctx.strokeStyle='#b5a48130';pctx.lineWidth=1;for(let y=70;y<H;y+=48){pctx.beginPath();pctx.moveTo(40,y);pctx.lineTo(W-40,y);pctx.stroke();}pctx.fillStyle='#9d8861';pctx.font='17px Georgia';pctx.fillText('AFTER HOURS / FIELD NOTES',45,35);for(const s of strokes)drawStroke(pctx,s);paperTex.needsUpdate=true;}
 redraw();updatePaper();
 function saveInk(){try{localStorage.setItem(INK_KEY,JSON.stringify(strokes));dirty=false;revision++;updatePaper();$('.ink-status').textContent='已保存 · 刷新后可继续';return true;}catch{$('.ink-status').textContent='保存失败，请导出 PNG 保留笔迹';return false;}}
 function position(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height)),p:e.pointerType==='pen'?Math.max(.12,e.pressure):.5};}
 canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);active={color:ink,size,points:[position(e)]};redo=[];drawStroke(ctx,active);});
 canvas.addEventListener('pointermove',e=>{const r=canvas.parentElement.getBoundingClientRect();cursor.style.left=(e.clientX-r.left)+'px';cursor.style.top=(e.clientY-r.top)+'px';cursor.style.display=e.pointerType==='touch'?'none':'block';if(!active)return;for(const ev of (e.getCoalescedEvents?.()||[e])){const last=active.points.at(-1),p=position(ev);if(Math.hypot(p.x-last.x,p.y-last.y)<.0005)continue;active.points.push(p);drawStroke(ctx,{...active,points:[last,p]});}});
 function finishStroke(){if(!active)return;strokes.push(active);active=null;dirty=true;$('.ink-status').textContent=`${strokes.length} 笔 · 尚未保存`;updatePaper();}
 canvas.addEventListener('pointerup',finishStroke);canvas.addEventListener('pointercancel',finishStroke);canvas.addEventListener('pointerleave',()=>{cursor.style.display='none';});
 $('#ink-size').oninput=e=>size=Number(e.target.value);document.querySelectorAll('[data-ink]').forEach(el=>el.onclick=()=>{ink=el.dataset.ink;document.querySelectorAll('[data-ink]').forEach(b=>b.classList.toggle('active',b===el));});
 $('#ink-undo').onclick=()=>{finishStroke();if(strokes.length)redo.push(strokes.pop());dirty=true;redraw();updatePaper();$('.ink-status').textContent=`${strokes.length} 笔 · 尚未保存`;};
 $('#ink-redo').onclick=()=>{if(redo.length)strokes.push(redo.pop());dirty=true;redraw();updatePaper();};
 $('#ink-clear').onclick=()=>{redo.push(...[...strokes].reverse());strokes=[];dirty=true;redraw();updatePaper();$('.ink-status').textContent='已清空 · 点击重做逐笔恢复';};
 $('#ink-save').onclick=saveInk;
 $('#ink-export').onclick=()=>{updatePaper();const a=document.createElement('a');a.download='雨夜书房-手写笔迹.png';a.href=paperTextureCanvas.toDataURL('image/png');a.click();$('.ink-status').textContent='已导出 PNG';};
 function setBlock(){const block=mode!==null;S.readerOpen=mode==='book';S.noteOpen=mode==='writing';S.typing=block;controls.enabled=!block;renderer.domElement.style.pointerEvents=block?'none':'auto';}
 function focusTrap(e){if(mode===null)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close();return;}if(e.key==='Tab'){const root=mode==='book'?bookUI:writing;const els=[...root.querySelectorAll('button:not(:disabled),select,input')].filter(el=>el.offsetParent!==null);if(!els.length)return;const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
 document.addEventListener('keydown',focusTrap,true);
 function renderBook(){const b=library[bookIndex],c=b.chapters[chapter];$('#volume-title').textContent=b.title;$('.book-subtitle').textContent=b.subtitle;$('.book-art').src=b.image;$('.book-art').alt=b.title+' · Image 生成插图';$('.book-chapter').textContent=c.title;$('.book-copy').replaceChildren(...c.text.map(t=>{const p=document.createElement('p');p.textContent=t;return p;}));$('#page-count').textContent=String(chapter*2+2).padStart(2,'0')+' / 06';$('#prev-chapter').disabled=chapter===0;$('#next-chapter').disabled=chapter===b.chapters.length-1;$('.chapter-select').replaceChildren(...b.chapters.map((c,i)=>{const o=document.createElement('option');o.value=i;o.textContent=c.title;o.selected=i===chapter;return o;}));$('.book-binding').style.background=b.color;}
 let turning=false;
 function turn(n){if(turning||n<0||n>=library[bookIndex].chapters.length||n===chapter)return;turning=true;$('.book-spread').classList.add('turning');setTimeout(()=>{chapter=n;renderBook();try{localStorage.setItem('afterhours.chapter.'+bookIndex,String(n));}catch{}},240);setTimeout(()=>{$('.book-spread').classList.remove('turning');turning=false;},570);}
 $('#prev-chapter').onclick=()=>turn(chapter-1);$('#next-chapter').onclick=()=>turn(chapter+1);$('.chapter-select').onchange=e=>turn(Number(e.target.value));
 function beginFlight(source,kind,onArrive){if(flight){scene.remove(flight.object);if(selectedSource)selectedSource.visible=true;flight=null;}selectedSource=source;source.visible=false;const clone=source.clone();clone.visible=true;clone.position.copy(source.getWorldPosition(new THREE.Vector3()));clone.quaternion.copy(source.getWorldQuaternion(new THREE.Quaternion()));scene.add(clone);const start=clone.position.clone(),fromQ=clone.quaternion.clone();const destination=camera.position.clone().add(camera.getWorldDirection(new THREE.Vector3()).multiplyScalar(2.1));const targetQ=camera.quaternion.clone();if(kind==='paper')targetQ.multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),0));flight={object:clone,source,start,end:destination,fromQ,toQ:targetQ,progress:0,kind,onArrive,returning:false};}
 function openBook(i){if(!library[i])return;if(mode)close(true);returnFocus=document.activeElement;bookIndex=i;chapter=Math.max(0,Math.min(2,Number(localStorage.getItem('afterhours.chapter.'+i)||0)));mode='book';S.selectedBook=i;setBlock();renderBook();const source=bookMeshes.find(b=>b.userData.book===i);beginFlight(source,'book',()=>{bookUI.classList.add('visible');$('#return-book').focus();});}
 
 function openWriting(){if(mode)close(true);returnFocus=document.activeElement;mode='writing';S.selectedBook=null;setBlock();beginFlight(note,'paper',()=>{writing.classList.add('visible');$('#return-paper').focus();});pen.visible=false;const carried=pen.clone();carried.visible=true;scene.add(carried);flight.pen=carried;flight.penStart=pen.position.clone();redraw();}
 function close(immediate=false){clearTimeout(openTimer);if(mode==='writing'){finishStroke();if(dirty)saveInk();pen.visible=true;}bookUI.classList.remove('visible');writing.classList.remove('visible');mode=null;S.selectedBook=null;setBlock();if(flight){if(immediate){scene.remove(flight.object);if(flight.pen)scene.remove(flight.pen);flight.source.visible=true;flight=null;}else{flight.object.visible=true;flight.start=flight.object.position.clone();flight.end=flight.source.position.clone();flight.fromQ=flight.object.quaternion.clone();flight.toQ=flight.source.quaternion.clone();flight.progress=0;flight.returning=true;}}if(returnFocus?.isConnected)returnFocus.focus();}
 $('#return-book').onclick=()=>close();$('#return-paper').onclick=()=>close();
 const extra=document.createElement('button');extra.id='writing-entry';extra.textContent='拿起纸笔 · 自由手写';extra.onclick=openWriting;$('#side').insertBefore(extra,$('#side').firstChild);
 const noteEntry=$('#open-note');noteEntry.querySelector('span').textContent='拿起桌上纸笔';const hint=noteEntry.previousElementSibling;if(hint)hint.textContent='点击纸张或钢笔，直接手写；笔迹会留在桌上。';
 // The pen is a real pick target too; keep ray hits on existing books and paper in the original router.
 const pick=new THREE.Raycaster(),uv=new THREE.Vector2();let down=null;
 renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});
 renderer.domElement.addEventListener('pointerup',e=>{if(mode||!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>7)return;uv.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);pick.setFromCamera(uv,camera);if(pick.intersectObject(pen).length)openWriting();down=null;});
 // Add intimate scale, objects and warmer materials to the sparse V1 room.
 const wood=new THREE.MeshStandardMaterial({color:0x4b3825,roughness:.82});const brass=new THREE.MeshStandardMaterial({color:0xb59957,metalness:.65,roughness:.35});
 function box(w,h,d,x,y,z,material){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;}
 for(let x=-8;x<8;x+=1.3){box(1.24,1.65,.07,x,.83,-ROOM.D/2+.27,wood);box(1.24,.055,.12,x,1.7,-ROOM.D/2+.31,brass);}
 for(let z=-6;z<6;z+=1.3){box(.08,1.65,1.24,-ROOM.W/2+.26,.83,z,wood);}
 const artFrame=box(2.9,2.1,.09,3.55,4.1,-ROOM.D/2+.28,wood);const painting=new THREE.Mesh(new THREE.PlaneGeometry(2.62,1.75),new THREE.MeshStandardMaterial({map:art[0],roughness:.85}));painting.position.set(3.55,4.1,-ROOM.D/2+.34);scene.add(painting);
 function plant(x,z,scale=1){const g=new THREE.Group();const pot=new THREE.Mesh(new THREE.CylinderGeometry(.28,.19,.5,28),new THREE.MeshStandardMaterial({color:0x827057,roughness:.9}));pot.position.y=.25;g.add(pot);for(let i=0;i<13;i++){const angle=i*2.399,stemH=.6+(i%4)*.2;const stem=new THREE.Mesh(new THREE.CylinderGeometry(.012,.017,stemH,6),new THREE.MeshStandardMaterial({color:0x3c5130}));stem.position.set(Math.cos(angle)*.12,.5+stemH/2,Math.sin(angle)*.12);g.add(stem);const leaf=new THREE.Mesh(new THREE.SphereGeometry(1,14,8),new THREE.MeshStandardMaterial({color:i%2?0x526b3b:0x2c5038,roughness:.75}));leaf.scale.set(.15,.035,.4);leaf.position.set(Math.cos(angle)*.32,.6+stemH,Math.sin(angle)*.32);leaf.rotation.set(.3,angle,.2);g.add(leaf);}g.position.set(x,0,z);g.scale.setScalar(scale);g.traverse(o=>{if(o.isMesh)o.castShadow=true;});scene.add(g);}
 plant(6.4,-4.6,1.9);plant(-6.9,2.9,1.5);
 // Soft wall lighting, avoiding a flat uniformly bright room.
 const fill=new THREE.PointLight(0xffd39b,15,13,2);fill.position.set(2.5,3.8,2.6);scene.add(fill);
 const wallwash=new THREE.PointLight(0xd6bc85,9,11,2);wallwash.position.set(-2.5,4,-3.6);scene.add(wallwash);
 const paperHalo=new THREE.PointLight(0xffd9a5,2,3,2);paperHalo.position.set(DESK.x,2.1,DESK.z);scene.add(paperHalo);
 const weather=createWeather({scene,glass,sky,camera,WIN,ROOM,rain});
 function update(t,dt){if(flight){const f=flight;f.progress=Math.min(1,f.progress+dt/.8);const u=f.progress,e=1-Math.pow(1-u,3);f.object.position.lerpVectors(f.start,f.end,e);f.object.position.y+=Math.sin(u*Math.PI)*.22;f.object.quaternion.slerpQuaternions(f.fromQ,f.toQ,e);if(f.pen){f.pen.visible=f.object.visible;const destination=f.object.position.clone().add(new THREE.Vector3(.35,.1,.1));f.pen.position.lerpVectors(f.penStart,destination,e);}if(u>=1){if(f.returning){scene.remove(f.object);if(f.pen)scene.remove(f.pen);f.source.visible=true;flight=null;}else if(f.onArrive){const cb=f.onArrive;f.onArrive=null;cb();f.object.visible=false;if(f.pen)f.pen.visible=false;}}}weather.update(t,dt,S.weather);fill.intensity=S.weather==='rain'?15:4;wallwash.intensity=S.weather==='rain'?9:3;}
 return {openBook,openWriting,close,update,snapshot:()=>({mode,bookIndex,chapter,chapterTitle:library[bookIndex].chapters[chapter]?.title,strokes:strokes.length,points:strokes.reduce((n,s)=>n+s.points.length,0),dirty,revision,bookTaken:!!selectedSource&&!selectedSource.visible,flightProgress:flight?.progress??null,...weather.snapshot()})};
}
